feat: Weak password mandatory modification
sdutacm/onlinejudge3-be pull request #3
Opened 2023-11-15 15:28 UTC by cooper-xs

2023-11-16 08:16 UTC, dreamerblue requested changes

2023-11-16 08:16 UTC, dreamerblue commented on src/app/user/user.controller.ts
> +      .body as IResetUserPasswordAndEmailReq;
怎么会有这么奇怪的格式化捏

2023-11-16 08:16 UTC, dreamerblue commented on src/app/user/user.controller.ts
> +    };
可以去掉自动登录

2023-11-16 15:26 UTC, cooper-xs commented on src/app/user/user.controller.ts
> +      .body as IResetUserPasswordAndEmailReq;
你别说你还真别说, 这还真是prettier给我格式化的, 不换行的话会过长

2023-11-16 15:34 UTC, cooper-xs commented on src/app/user/user.controller.ts
> +    };
已修正

2023-11-17 03:41 UTC, dreamerblue commented on src/app/user/user.controller.ts
> +      .body as IResetUserPasswordAndEmailReq;
啊？插件加载没问题吧？
应该格式化成这样才符合预期
```
const {
  username,
  oldPassword,
  email,
  code,
  password,
} = ctx.request.body as IResetUserPasswordAndEmailReq;
```

2023-11-17 03:42 UTC, dreamerblue requested changes

2023-11-17 03:42 UTC, dreamerblue commented on src/app/user/user.controller.ts
> +    return;
可省略return

2023-11-17 03:47 UTC, cooper-xs commented on src/app/user/user.controller.ts
> +      .body as IResetUserPasswordAndEmailReq;
好捏

2023-11-17 03:47 UTC, cooper-xs commented on src/app/user/user.controller.ts
> +    return;
已删除

2023-11-18 02:51 UTC, dreamerblue approved these changes

2023-11-18 04:52 UTC, merged